### ISSUE TITLE
Can't build the project, compile errors

### ISSUE THREAD

**Issue by OlafSzmidt** [stormpath/stormpath-spring-boot-jpa-example#1]
Using the following command:

`mvn spring-boot:run`

I receive the following:

> [WARNING] 
> java.lang.reflect.InvocationTargetException
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-internal/Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(java.base@9-internal/NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-internal/DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(java.base@9-internal/Method.java:531)
>     at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:478)
>     at java.lang.Thread.run(java.base@9-internal/Thread.java:804)
> Caused by: org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat servlet container
>     at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:165)
>     at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:293)
>     at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141)
>     at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
>     at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
>     at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760)
>     at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360)
>     at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
>     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
>     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
>     at demo.Application.main(Application.java:10)
>     ... 6 more
> Caused by: java.lang.IllegalStateException: Tomcat connector in failed state
>     at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:159)
>     ... 16 more

**Comment by rewotiraj** [comment]
(EmbeddedWebApplicationContext.java:293)
how to solve this type of error
